[package]
name = "emulator-native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.8.0"
rodio = "0.14.0"
winit = "0.25.0"
emulator-core = { path = "../emulator-core" }
